"""Stage 2: industrial reuse and community transition, for a county the national model shortlisted.

An explanation and site-screening layer after the ranking. Nothing here feeds rank(): no pillar,
weight, gate, or preset reads these functions. The output is evidence to read, not a score.

Economic need is not evidence of community support. Nothing in this module measures, infers, or
reports community sentiment.
"""
from pathlib import Path

import pandas as pd

SUPPORT_DISCLAIMER = ("Economic need is not evidence of community support. Local engagement and "
                      "project-level validation are still required.")
BROWNFIELD_CAVEAT = ("EPA brownfield records mark properties with a cleanup or assessment history. They "
                     "are potential reuse candidates, not confirmed available land and not confirmed "
                     "data-center sites.")
SITES_ABSENT = ("Site-level brownfield details aren't available here: data/processed/brownfield_sites.parquet "
                "is generated by the ETL (python -m etl.build_features) and isn't committed. The county "
                "totals below come from the committed feature table.")
VERIFICATION = [
    "Utility capacity: whether the utility can serve the load, on what timeline, and at what cost.",
    "Site ownership and availability: who owns each candidate property and whether it is for sale or lease.",
    "Cleanup status: what EPA and the state require before reuse, and any institutional controls.",
    "Zoning: whether data centers are a permitted use and what rezoning or variances would need.",
    "Water and air permits: cooling water rights or supply, and permits for backup generators.",
    "Transmission upgrades: substation and line work the interconnection study would require.",
    "Local engagement: what residents, local officials, and workers want, learned directly from them.",
    "Tax and community-benefit agreements: abatements, payments in lieu of taxes, hiring, and benefits.",
]

# (column, label, format). Formats: pct (0-100 value), frac (0-1 shown as %), pp (fraction change shown
# as percentage points), count, signed, mw, acres, flag, text.
SECTIONS = {
    "Economic transition": [
        ("unemployment_rate_pct_2024", "Unemployment rate, 2024", "pct"),
        ("unemployment_rate_pct_3yr_2022_2024", "Unemployment rate, pooled 2022-2024", "pct"),
        ("mfg_emp_2015", "Manufacturing jobs, 2015 (QCEW, private)", "count"),
        ("mfg_emp_2024", "Manufacturing jobs, 2024 (QCEW, private)", "count"),
        ("mfg_emp_change_2015_2024", "Manufacturing jobs gained or lost, 2015-2024", "signed"),
        ("mfg_emp_pct_change_2015_2024", "Manufacturing employment change, 2015-2024", "frac_signed"),
        ("mfg_emp_share_1969", "Manufacturing share of jobs, 1969 (BEA)", "frac"),
        ("mfg_emp_share_change_1969_2022", "Change in manufacturing share, 1969-2022", "pp"),
        ("pop_change_pct_since_peak", "Population change from historical peak", "pct_signed"),
        ("ers_low_employment_2025", "USDA low-employment county (ACS 2018-2022)", "flag"),
        ("ers_population_loss_2025", "USDA population-loss county (2000-2020)", "flag"),
        ("rucc_2023_description", "Rural-urban classification (USDA RUCC 2023)", "text"),
        ("ers_industry_dependence_2025", "Industry dependence (USDA, 2019-2022 average)", "text"),
    ],
    "Industrial reuse": [
        ("bf_site_count", "EPA brownfield properties", "count"),
        ("bf_known_acres_sites", "Properties with reported acreage", "count"),
        ("bf_known_acres", "Total reported acreage", "acres"),
        ("bf_acreage_reporting_share", "Acreage reporting coverage", "frac"),
        ("bf_sites_50plus_acres", "Properties of at least 50 reported acres", "count"),
        ("bf_ready_for_reuse_count", "Properties EPA lists as ready for reuse", "count"),
        ("coal_retired_mw", "Retired coal capacity (EIA-860)", "mw"),
        ("energy_community_coal_closure", "IRA energy community: coal closure tract", "flag"),
        ("energy_community_ffe", "IRA energy community: fossil employment area", "flag"),
    ],
    "Infrastructure context": [
        ("plant_capacity_mw_100km", "Generation within 100 km (all fuels)", "mw"),
        ("plant_clean_capacity_mw_100km", "Clean generation within 100 km", "mw"),
        ("fiber_share_locations", "Locations with fiber (last mile)", "frac"),
        ("dc_existing_count", "Existing data centers (FracTracker)", "count"),
        ("dc_existing_mw_reported", "Existing data-center MW, where reported", "mw"),
        ("dc_existing_mw_reporting_share", "Existing facilities reporting MW", "frac"),
        ("dc_proposed_count", "Proposed data centers (FracTracker)", "count"),
        ("dc_proposed_mw_reported", "Proposed data-center MW, where reported", "mw"),
        ("dc_proposed_mw_reporting_share", "Proposed facilities reporting MW", "frac"),
        ("queue_active_mw_clean_excl_storage", "Clean generation in the queue, excluding storage", "mw"),
        ("queue_active_mw_storage_standalone", "Standalone storage in the queue (not generation)", "mw"),
        ("queue_operational_mw_online_5y", "Queue capacity delivered or estimated online, 2021-2025", "mw"),
        ("queue_operational_online_date_fallback_share", "Delivered projects dated by proposed online date", "frac"),
    ],
}
NUMERIC = {"pct", "pct_signed", "frac", "frac_signed", "pp", "count", "signed", "mw", "acres"}
# Percentiles rank the raw value, not how favorable it is. Where that is easy to misread, say how.
DECLINE = "Low percentile = steeper decline"
READING = {"unemployment_rate_pct_2024": "High percentile = more unemployment",
           "unemployment_rate_pct_3yr_2022_2024": "High percentile = more unemployment",
           "mfg_emp_change_2015_2024": DECLINE, "mfg_emp_pct_change_2015_2024": DECLINE,
           "mfg_emp_share_change_1969_2022": DECLINE, "pop_change_pct_since_peak": DECLINE,
           "queue_operational_online_date_fallback_share": "High percentile = more reliance on proposed dates"}
PERCENTILE_NOTE = ("National percentile ranks the raw value from lowest (0) to highest (100), counting ties as "
                   "half. It isn't a score: for a decline measure, the 1st percentile is one of the steepest "
                   "losses in the country, not a good result.")
# A share with nothing to divide is undefined, not missing: (column it divides by, what to show).
UNDEFINED_WHEN_ZERO = {"bf_acreage_reporting_share": ("bf_site_count", "no properties"),
                       "dc_existing_mw_reporting_share": ("dc_existing_count", "no facilities"),
                       "dc_proposed_mw_reporting_share": ("dc_proposed_count", "no facilities"),
                       "queue_operational_online_date_fallback_share":
                           ("queue_operational_projects_online_5y", "no delivered projects")}
MAP_OPTIONS = {"mfg_jobs_lost_2015_2024": "Manufacturing jobs lost, 2015-2024",
               "unemployment_rate_pct_2024": "Unemployment rate, 2024",
               "bf_site_count": "EPA brownfield properties",
               "bf_ready_for_reuse_count": "Brownfields ready for reuse"}
SITE_COLUMNS = {"property_name": "Property", "city": "City", "state": "State",
                "acreage_reported": "Reported acres", "ready_for_reuse": "Ready for reuse",
                "planned_future_use": "Planned future use", "substation_dist_mi": "Substation (mi)",
                "substation_voltage_kv": "Substation (kV)", "transmission_line_dist_mi": "Transmission line (mi)",
                "transmission_line_kv": "Transmission line (kV)", "rail_dist_mi": "Rail (mi)",
                "cimc_profile_url": "EPA profile"}


def _derived(df):
    """Columns the profile needs that the table stores implicitly."""
    out = df
    if {"bf_site_count", "bf_acreage_reporting_share"} <= set(df.columns):
        known = (df["bf_site_count"].astype("Float64") * df["bf_acreage_reporting_share"].astype("Float64")).round()
        known = known.mask(df["bf_site_count"] == 0, 0)
        out = out.assign(bf_known_acres_sites=known.astype("Int64"))
    return out


def national_stats(df):
    """Median and sorted non-null values for every numeric profile column, across all counties."""
    df = _derived(df)
    stats = {}
    for rows in SECTIONS.values():
        for col, _, fmt in rows:
            if fmt in NUMERIC and col in df.columns:
                v = pd.to_numeric(df[col], errors="coerce").dropna()
                if len(v):
                    stats[col] = {"median": float(v.median()), "values": v.sort_values().to_numpy()}
    return stats


def _percentile(stats, col, x):
    """Mid-rank national percentile, 0-100: counties below x plus half of those tied with it.
    Ties matter here because many columns are 0 in most counties."""
    vals = stats[col]["values"]
    below, tied = float((vals < x).sum()), float((vals == x).sum())
    return 100.0 * (below + tied / 2) / len(vals)


def fmt(value, kind):
    if value is None or (not isinstance(value, str) and pd.isna(value)):
        return "not available"
    if kind == "pct":
        return f"{value:.1f}%"
    if kind == "pct_signed":
        return "0.0% (at peak)" if value == 0 else f"{value:+.1f}%"
    if kind == "frac":
        return f"{value:.0%}"
    if kind == "frac_signed":
        return f"{value:+.0%}"
    if kind == "pp":
        return f"{100 * value:+.1f} points"
    if kind == "signed":
        return f"{value:+,.0f}"
    if kind in ("count",):
        return f"{value:,.0f}"
    if kind == "mw":
        return f"{value:,.0f} MW"
    if kind == "acres":
        return f"{value:,.1f} acres"
    if kind == "flag":
        return "yes" if bool(value) else "no"
    return str(value)


def profile(df, fips, stats=None):
    """Sections of rows for one county: value, national median, and national percentile.

    Missing columns or null values show "not available" and are listed in missing. Nothing is
    filled in or estimated.
    """
    df = _derived(df)
    stats = stats if stats is not None else national_stats(df)
    hit = df.index[df["fips"] == fips]
    if not len(hit):
        raise KeyError(f"fips {fips} not in the feature table")
    row = df.loc[hit[0]]
    out = {"fips": fips, "county": f"{row.get('county_name', '')}, {row.get('state', '')}", "sections": {},
           "missing": [], "values": {}, "present": set(df.columns)}
    for section, rows in SECTIONS.items():
        items = []
        for col, label, kind in rows:
            raw = row[col] if col in df.columns else None
            if raw is not None and not isinstance(raw, str) and pd.isna(raw):
                raw = None
            item = {"column": col, "label": label, "value": raw, "display": fmt(raw, kind),
                    "national_median": None, "national_percentile": None, "reading": READING.get(col, "")}
            if kind in NUMERIC and col in stats:
                item["national_median"] = fmt(stats[col]["median"], kind)
                if raw is not None:
                    item["national_percentile"] = round(_percentile(stats, col, float(raw)))
            if raw is None and col in UNDEFINED_WHEN_ZERO:
                denom, text = UNDEFINED_WHEN_ZERO[col]
                if denom in df.columns and row[denom] == 0:
                    item["display"] = text
            if raw is None and item["display"] == "not available":
                out["missing"].append(label)
            items.append(item)
            out["values"][col] = raw
        out["sections"][section] = items
    if out["values"].get("bf_site_count") and out["values"].get("bf_known_acres") is None:
        for item in out["sections"]["Industrial reuse"]:
            if item["column"] == "bf_known_acres":
                item["display"] = "not reported for any property"
    return out


def benefits(p):
    """Evidence statements about economic transition and reuse. They describe need and assets in the
    data; none of them says the community wants a data center."""
    v, out = p["values"], []
    lost, pct = v.get("mfg_emp_change_2015_2024"), v.get("mfg_emp_pct_change_2015_2024")
    if lost is not None and lost < 0:
        out.append(f"Manufacturing employment fell by {-lost:,.0f} jobs from 2015 to 2024"
                   + (f" ({pct:+.0%})." if pct is not None else "."))
    share69, change = v.get("mfg_emp_share_1969"), v.get("mfg_emp_share_change_1969_2022")
    if share69 is not None and change is not None and change < -0.1:
        out.append(f"Manufacturing was {share69:.0%} of jobs in 1969 and its share has fallen "
                   f"{-100 * change:.0f} points since, a long-run industrial legacy.")
    u = v.get("unemployment_rate_pct_3yr_2022_2024")
    med = next((i["national_median"] for i in p["sections"]["Economic transition"]
                if i["column"] == "unemployment_rate_pct_3yr_2022_2024"), None)
    pctl = next((i["national_percentile"] for i in p["sections"]["Economic transition"]
                 if i["column"] == "unemployment_rate_pct_3yr_2022_2024"), None)
    if u is not None and pctl is not None and pctl >= 75:
        out.append(f"Unemployment averaged {u:.1f}% in 2022-2024, above {pctl}% of counties (national median {med}).")
    peak = v.get("pop_change_pct_since_peak")
    if peak is not None and peak <= -10:
        out.append(f"Population is {-peak:.0f}% below its historical peak.")
    if v.get("ers_low_employment_2025"):
        out.append("USDA classifies it as a low-employment county.")
    if v.get("energy_community_coal_closure") or v.get("energy_community_ffe"):
        out.append("It is in an IRA energy community, which can qualify projects for bonus federal tax credits.")
    coal = v.get("coal_retired_mw")
    if coal:
        out.append(f"{coal:,.0f} MW of coal capacity has retired, which can leave transmission and "
                   "interconnection points worth investigating.")
    n, ready, big = v.get("bf_site_count"), v.get("bf_ready_for_reuse_count"), v.get("bf_sites_50plus_acres")
    if n:
        out.append(f"EPA lists {n:,} brownfield properties here ({ready or 0:,} ready for reuse, "
                   f"{big or 0:,} of at least 50 reported acres) that could be screened as reuse candidates.")
    if not out:
        out.append("The data shows no strong economic-transition or industrial-reuse signal for this county. "
                   "Any community benefit would have to be established locally.")
    return out


def verification(p):
    """Standard local checks, plus county-specific data gaps that make them more pressing."""
    v, extra = p["values"], []
    if v.get("bf_site_count") and v.get("bf_known_acres") is None:
        extra.append("No brownfield property here reports acreage; measure candidate parcels directly.")
    share = v.get("queue_operational_online_date_fallback_share")
    if share is not None and share >= 0.5:
        extra.append(f"{share:.0%} of recently delivered queue projects here are dated by their proposed, "
                     "not actual, online date; confirm delivered capacity with the utility.")
    if {"mfg_emp_2015", "mfg_emp_2024"} <= p["present"] and any(v.get(f"mfg_emp_{y}") is None for y in (2015, 2024)):
        extra.append("Manufacturing employment is suppressed or unavailable for at least one year; check "
                     "state labor-market data.")
    return VERIFICATION + extra


def risks(e, p):
    """Key risks from the explanation (gates, weak pillars, warnings) and the county profile."""
    out = []
    if not e["passed_gates"]:
        out.append("Excluded by: " + ", ".join(e["failed_gates"]))
    if e.get("unknown_gates"):
        out.append("No data for gates (not excluded): " + ", ".join(e["unknown_gates"]))
    out += e.get("warnings", [])
    for pillar, d in e["pillars"].items():
        pct = d.get("national_percentile")
        if pct is not None and pct < 25:
            out.append(f"Weak {pillar.replace('_', ' ')} pillar: national percentile {pct:.0f}.")
    if e.get("floor_ok") is False:
        out.append("Below the pillar floor on at least one pillar.")
    return out or ["No gate failures, warnings, or pillars below the 25th national percentile."]


def load_sites(path):
    """The generated brownfield site table, or None when the ETL hasn't produced it."""
    path = Path(path)
    if not path.exists():
        return None
    return pd.read_parquet(path)


def county_sites(sites, fips):
    """Candidate properties for one county, largest reported acreage first, with readable columns."""
    if sites is None:
        return None
    s = sites[sites["fips"] == fips]
    s = s.sort_values("acreage_reported", ascending=False, na_position="last")
    cols = [c for c in SITE_COLUMNS if c in s.columns]
    out = s[cols].rename(columns=SITE_COLUMNS).reset_index(drop=True)
    if "Ready for reuse" in out:
        out["Ready for reuse"] = out["Ready for reuse"].map({True: "yes", False: "no"}).fillna("not reported")
    if "Planned future use" in out:
        out["Planned future use"] = out["Planned future use"].astype("string").fillna("not reported")
    return out


def brief(e, p, sites=None):
    """Plain Markdown screening brief for download."""
    lines = [f"# County screening brief: {p['county']} ({p['fips']})", "",
             f"> {SUPPORT_DISCLAIMER}", "",
             f"Conditions: {e.get('conditions')}, horizon {e.get('horizon')}.", "",
             "Stage 2 is unscored, post-ranking screening. It doesn't change this county's rank.", "",
             PERCENTILE_NOTE, ""]
    if e["passed_gates"]:
        lines.append(f"**Rank {e['rank']} of {e['of']}**, composite {e['composite']:.1f}, "
                     f"robustness {'n/a' if e['robustness'] is None else format(e['robustness'], '.0%')}, "
                     f"coverage {e['coverage']:.0%}.")
    else:
        lines.append("**Not ranked.** Excluded by: " + ", ".join(e["failed_gates"]) + ".")
    lines += ["", "## Pillar scores", "", "| Pillar | Score | National percentile | Weight |", "| --- | ---: | ---: | ---: |"]
    for pillar, d in e["pillars"].items():
        s = "n/a" if d["score"] is None else f"{d['score']:.1f}"
        n = "n/a" if d["national_percentile"] is None else f"{d['national_percentile']:.0f}"
        lines.append(f"| {pillar.replace('_', ' ')} | {s} | {n} | {d['weight']:.0%} |")
    for section, rows in p["sections"].items():
        lines += ["", f"## {section}", "", "| Measure | County | National median | National percentile | How to read |",
                  "| --- | ---: | ---: | ---: | --- |"]
        for r in rows:
            pct = "" if r["national_percentile"] is None else str(r["national_percentile"])
            lines.append(f"| {r['label']} | {r['display']} | {r['national_median'] or ''} | {pct} | {r['reading']} |")
    if sites is not None and len(sites):
        lines += ["", f"Candidate brownfield properties: {len(sites)} (site list exported separately).",
                  "", BROWNFIELD_CAVEAT]
    lines += ["", "## Why this community could benefit", ""] + [f"- {b}" for b in benefits(p)]
    lines += ["", "## Key risks", ""] + [f"- {r}" for r in risks(e, p)]
    lines += ["", "## Missing data", ""] + ([f"- {m}" for m in p["missing"]] or ["- None of the profile fields is missing."])
    lines += ["", "## What still requires local verification", ""] + [f"- {x}" for x in verification(p)]
    lines += ["", f"> {SUPPORT_DISCLAIMER}", ""]
    return "\n".join(lines)
